[tool.poetry]
name = "telegram_bot_api_rest"
version = "0.1.0"
description = ""
authors = ["luisfer2405<lukfer2405@gmail.com>]

[tool.poetry.dependencies]
python = "^3.7"
flask = "*"
python-telegram-bot = "^13.1"
python-decouple = "^3.4"
requests ="^2.25.1"

[tool.poetry.dev-dependencies]
pdbpp = "^0.12.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"